# Generated by Django 2.2rc1 on 2019-05-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0024_auto_20190501_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='is_color_device',
            field=models.BooleanField(default=False),
        ),
    ]
