# Generated by Django 2.2rc1 on 2019-05-03 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0026_auto_20190502_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetFighterDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('requested_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreetFighterDrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('requested_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreetFighterToner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('requested_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='developer',
            name='unique_developer',
        ),
        migrations.RemoveConstraint(
            model_name='drum',
            name='unique_drum',
        ),
        migrations.RemoveConstraint(
            model_name='toner',
            name='unique_toner',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='name',
            new_name='part_id',
        ),
        migrations.RenameField(
            model_name='drum',
            old_name='name',
            new_name='part_id',
        ),
        migrations.RenameField(
            model_name='toner',
            old_name='name',
            new_name='part_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='is_street_fighter',
        ),
        migrations.AddField(
            model_name='developer',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='drum',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='manageralert',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manageralert',
            name='resolve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='manageralert',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mps.MPS_User'),
        ),
        migrations.AddField(
            model_name='manageralert',
            name='was_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='street_fighter_status',
            field=models.IntegerField(choices=[(0, 'No Street Fighter'), (1, 'Pending'), (2, 'Approved'), (3, 'Declined')], default=0),
        ),
        migrations.AddField(
            model_name='toner',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='manageralert',
            name='alert_type',
            field=models.CharField(choices=[('street_fighter', 'Street Fighter'), ('margin', 'Margin')], max_length=25),
        ),
        migrations.AddConstraint(
            model_name='developer',
            constraint=models.UniqueConstraint(fields=('part_id', 'company', 'manufacturer', 'printer', 'part_color'), name='unique_developer'),
        ),
        migrations.AddConstraint(
            model_name='drum',
            constraint=models.UniqueConstraint(fields=('part_id', 'company', 'manufacturer', 'printer', 'part_color'), name='unique_drum'),
        ),
        migrations.AddConstraint(
            model_name='toner',
            constraint=models.UniqueConstraint(fields=('part_id', 'company', 'manufacturer', 'printer', 'part_color'), name='unique_toner'),
        ),
        migrations.AddField(
            model_name='streetfightertoner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Company'),
        ),
        migrations.AddField(
            model_name='streetfightertoner',
            name='original_toner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Toner'),
        ),
        migrations.AddField(
            model_name='streetfightertoner',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Printer'),
        ),
        migrations.AddField(
            model_name='streetfightertoner',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Proposal'),
        ),
        migrations.AddField(
            model_name='streetfighterdrum',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Company'),
        ),
        migrations.AddField(
            model_name='streetfighterdrum',
            name='original_drum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Drum'),
        ),
        migrations.AddField(
            model_name='streetfighterdrum',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Printer'),
        ),
        migrations.AddField(
            model_name='streetfighterdrum',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Proposal'),
        ),
        migrations.AddField(
            model_name='streetfighterdeveloper',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Company'),
        ),
        migrations.AddField(
            model_name='streetfighterdeveloper',
            name='original_developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Developer'),
        ),
        migrations.AddField(
            model_name='streetfighterdeveloper',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Printer'),
        ),
        migrations.AddField(
            model_name='streetfighterdeveloper',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Proposal'),
        ),
    ]
