# Generated by Django 2.2rc1 on 2019-05-03 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0028_auto_20190503_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
