# Generated by Django 2.2rc1 on 2019-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0031_auto_20190504_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalserviceitem',
            name='non_network_cost',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='base_rate_mono',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='base_volume_mono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='mono_coverage',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='mono_toner_price',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='proposed_cpp_mono',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='total_mono_pages',
            field=models.IntegerField(null=True),
        ),
    ]
