# Generated by Django 2.2rc1 on 2019-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0032_auto_20190504_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalserviceitem',
            old_name='tier_level',
            new_name='tier_level_mono',
        ),
        migrations.RemoveField(
            model_name='proposalserviceitem',
            name='tier_values',
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='tier_level_color',
            field=models.CharField(default='none', max_length=10, null=True),
        ),
    ]
