# Generated by Django 2.2rc1 on 2019-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0034_auto_20190506_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetfighterdeveloper',
            name='new_price',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='streetfighterdrum',
            name='new_price',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='streetfightertoner',
            name='new_price',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10, null=True),
        ),
    ]
