# Generated by Django 2.2.1 on 2019-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0035_auto_20190506_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='drum',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='toner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
