# Generated by Django 2.2.1 on 2019-05-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0036_auto_20190508_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streetfighterdeveloper',
            old_name='original_developer',
            new_name='original_part',
        ),
        migrations.RenameField(
            model_name='streetfighterdrum',
            old_name='original_drum',
            new_name='original_part',
        ),
        migrations.RenameField(
            model_name='streetfightertoner',
            old_name='original_toner',
            new_name='original_part',
        ),
    ]
