# Generated by Django 2.2.1 on 2019-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0039_auto_20190517_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalserviceitem',
            name='rcmd_cpp_color',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='rcmd_cpp_mono',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
