# Generated by Django 2.2.1 on 2019-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0040_auto_20190521_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='non_network_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
