# Generated by Django 2.2.1 on 2019-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0040_auto_20190522_1500'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessory',
            name='unique_accessory',
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.UniqueConstraint(fields=('printer', 'part_number', 'company'), name='unique_accessory'),
        ),
    ]
