# Generated by Django 2.2.1 on 2019-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0041_auto_20190521_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='base_rate_color',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='base_rate_mono',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='base_volume_color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='base_volume_mono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='color_coverage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='color_toner_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='mono_coverage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='mono_toner_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='proposed_cpp_color',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='proposed_cpp_mono',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='rcmd_cpp_color',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='rcmd_cpp_mono',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='total_color_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalserviceitem',
            name='total_mono_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
