# Generated by Django 2.2.1 on 2019-05-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0042_auto_20190521_2053'),
        ('mps', '0041_auto_20190522_1550'),
    ]

    operations = [
    ]
