# Generated by Django 2.2.2 on 2019-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0046_auto_20190620_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tieredvalue',
            name='bw1_proposed_margin',
        ),
        migrations.RemoveField(
            model_name='tieredvalue',
            name='bw2_proposed_margin',
        ),
        migrations.RemoveField(
            model_name='tieredvalue',
            name='bw3_proposed_margin',
        ),
        migrations.RemoveField(
            model_name='tieredvalue',
            name='bw4_proposed_margin',
        ),
        migrations.RemoveField(
            model_name='tieredvalue',
            name='color1_proposed_margin',
        ),
        migrations.RemoveField(
            model_name='tieredvalue',
            name='color2_proposed_margin',
        ),
        migrations.RemoveField(
            model_name='tieredvalue',
            name='color3_proposed_margin',
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='bw1_cpp',
            field=models.DecimalField(decimal_places=5, default=0.015, max_digits=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='bw2_cpp',
            field=models.DecimalField(decimal_places=5, default=0.02, max_digits=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='bw3_cpp',
            field=models.DecimalField(decimal_places=5, default=0.04, max_digits=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='bw4_cpp',
            field=models.DecimalField(decimal_places=5, default=9999, max_digits=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='color1_cpp',
            field=models.DecimalField(decimal_places=5, default=0.06, max_digits=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='color2_cpp',
            field=models.DecimalField(decimal_places=5, default=0.1, max_digits=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='color3_cpp',
            field=models.DecimalField(decimal_places=5, default=9999, max_digits=12),
        ),
    ]
