# Generated by Django 2.2.1 on 2019-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0048_auto_20190620_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='bln_base_volume_color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='bln_base_volume_mono_on_color',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
