# Generated by Django 2.2.1 on 2019-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0049_auto_20190702_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieredvalue',
            name='bw1_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tieredvalue',
            name='bw2_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tieredvalue',
            name='bw3_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tieredvalue',
            name='bw4_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tieredvalue',
            name='color1_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tieredvalue',
            name='color2_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tieredvalue',
            name='color3_overage_cpp',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
