# Generated by Django 2.2.1 on 2019-07-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0050_auto_20190702_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start_range', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lease_end_range', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lease_rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leasing_company', models.CharField(max_length=100, unique=True)),
                ('lease_type', models.CharField(max_length=100)),
                ('lease_term', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Company')),
                ('lease_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.LeaseRange')),
            ],
        ),
    ]
