# Generated by Django 2.2.1 on 2019-07-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0051_lease_leaserange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='lease_term',
        ),
        migrations.AddField(
            model_name='leaserange',
            name='lease_term',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
