# Generated by Django 2.2.3 on 2019-07-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0054_pagecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mps.Company')),
            ],
        ),
    ]
