# Generated by Django 2.2.3 on 2019-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0055_accountsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(default='cpp', max_length=32),
        ),
    ]
