# Generated by Django 2.2.3 on 2019-08-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0056_proposal_proposal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='default_toner_type',
            field=models.CharField(choices=[('OEM', 'OEM'), ('REMAN', 'Reman'), ('OEM_SMP', 'OEM SMP')], default='OEM_SMP', max_length=10),
        ),
    ]
