# Generated by Django 2.2.1 on 2019-08-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0057_auto_20190802_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageralert',
            name='resolve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manageralert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mps.MPS_User'),
        ),
    ]
