# Generated by Django 2.2.1 on 2019-08-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0058_allow_manageralert_blanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printercost',
            name='product_id',
            field=models.CharField(max_length=50),
        ),
    ]
