# Generated by Django 2.2.2 on 2019-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0059_product_id_notunique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingcompany',
            name='leasing_company',
            field=models.CharField(max_length=100),
        ),
    ]
