# Generated by Django 2.2.2 on 2019-08-27 02:18

from django.db import migrations, models
import mps.models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0060_auto_20190822_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementassumption',
            name='eq_commission_type',
            field=models.CharField(choices=[('eq_flat_margin', 'EQ Flat % of Margin'), ('eq_flat_revenue', 'EQ Flat % of Revenue'), ('eq_blended_margin', 'EQ % of Margin - Blended Printer & Copier Rate'), ('eq_blended_revenue', 'EQ % of Revenue - Blended Printer & Copier Rate')], default='eq_flat_margin', max_length=40),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='eq_margin_rate_copiers',
            field=models.DecimalField(decimal_places=5, default=0.1, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='eq_margin_rate_printers',
            field=models.DecimalField(decimal_places=5, default=0.1, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='eq_percent_margin_flat_rate',
            field=models.DecimalField(decimal_places=5, default=0.1, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='eq_percentage_revenue_flat_rate',
            field=models.DecimalField(decimal_places=5, default=0.02, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='eq_revenue_rate_copiers',
            field=models.DecimalField(decimal_places=5, default=0.02, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='eq_revenue_rate_printers',
            field=models.DecimalField(decimal_places=5, default=0.02, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
        migrations.AlterField(
            model_name='pagecost',
            name='source',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('local', 'Local')], max_length=8),
        ),
    ]
