# Generated by Django 2.2.2 on 2019-09-03 13:45

from django.db import migrations, models


def populate_recommended_cartridge_prices(apps, schema_editor):
    ProposalServiceItem = apps.get_model('mps', 'ProposalServiceItem')
    Toner = apps.get_model('mps', 'Toner')
    Proposal = apps.get_model('mps', 'Proposal')


    for item in ProposalServiceItem.objects.all().select_related('printer'):
        proposal = Proposal.objects.get(id=item.proposal_id)
        if item.printer.mono_toner and item.rcmd_cpp_mono:
            mono_toner = Toner.objects.filter(
                company_id=proposal.sales_rep.company_id,
                printer_id=item.printer_id,
                part_color='mono',
            )[0]
            item.recommended_cost_per_cartridge_mono = mono_toner.yield_amount * item.rcmd_cpp_mono

        if item.printer.cyan_toner and item.rcmd_cpp_color:
            color_toner = Toner.objects.filter(
                company_id=proposal.sales_rep.company_id,
                printer_id=item.printer_id,
                part_color='cyan',
            )[0]
            item.recommended_cost_per_cartridge_color = (color_toner.yield_amount * item.rcmd_cpp_color) / 3

        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0061_auto_20190831_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalserviceitem',
            name='proposed_cost_per_cartridge_color',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='proposed_cost_per_cartridge_mono',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='recommended_cost_per_cartridge_color',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='recommended_cost_per_cartridge_mono',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
    ]
