# Generated by Django 2.2.1 on 2019-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0062_auto_20190903_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementassumption',
            name='toner_after_oem_smp',
            field=models.CharField(choices=[('OEM', 'OEM'), ('REMAN', 'Reman'), ('OEM_SMP', 'OEM SMP')], default='OEM', max_length=10),
        ),
        migrations.AlterField(
            model_name='managementassumption',
            name='toner_after_reman',
            field=models.CharField(choices=[('OEM', 'OEM'), ('REMAN', 'Reman'), ('OEM_SMP', 'OEM SMP')], default='OEM_SMP', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='default_toner_type',
            field=models.CharField(choices=[('OEM', 'OEM'), ('REMAN', 'Reman'), ('OEM_SMP', 'OEM SMP')], default='OEM_SMP', max_length=10),
        ),
    ]
