# Generated by Django 2.2.4 on 2019-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0063_auto_20190904_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementassumption',
            name='allow_ppc',
            field=models.BooleanField(default=False),
        ),
    ]
