# Generated by Django 2.2.4 on 2019-09-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0064_managementassumption_allow_ppc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementassumption',
            name='allow_ppc',
        ),
    ]
