# Generated by Django 2.2.4 on 2019-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0065_remove_managementassumption_allow_ppc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='zone_01',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proposal',
            name='zone_02',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proposal',
            name='zone_03',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
