# Generated by Django 2.2.4 on 2019-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0066_auto_20190920_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpurchaseitem',
            name='bundled_cpp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='proposalpurchaseitem',
            name='lease_buyout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
