# Generated by Django 2.2.4 on 2019-10-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0069_auto_20191014_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementassumption',
            name='cost_offset_12month',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='managementassumption',
            name='cost_offset_24month',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='managementassumption',
            name='cost_offset_36month',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='managementassumption',
            name='cost_offset_48month',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='managementassumption',
            name='cost_offset_60month',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
    ]
