# Generated by Django 2.2.4 on 2019-10-22 19:05

from django.db import migrations, models
import django.db.models.deletion
import mps.models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0070_auto_20191014_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_service_type', models.CharField(max_length=40, null=True, validators=[mps.models.validate_service_types])),
                ('default_toner_type', models.CharField(choices=[('OEM', 'OEM'), ('REMAN', 'Reman'), ('OEM_SMP', 'OEM SMP')], default='OEM_SMP', max_length=10)),
                ('total_supply_spend', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('total_service_spend', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('total_lease_spend', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('est_transaction_overhead', models.DecimalField(blank=True, decimal_places=5, default=60, max_digits=12, null=True)),
                ('total_sales_orders', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('total_service_orders', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.Client')),
                ('contract_service_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.ServiceLevel')),
            ],
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='allow_tco',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProposalTCOItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposalserviceitem_id', models.IntegerField(blank=True, null=True)),
                ('number_printers_serviced', models.IntegerField(blank=True, default=1, null=True)),
                ('total_mono_pages', models.IntegerField(blank=True, null=True)),
                ('total_color_pages', models.IntegerField(blank=True, null=True)),
                ('current_cpp_mono', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('current_cpp_color', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('rcmd_cpp_mono', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('rcmd_cpp_color', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('mono_toner_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('color_toner_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('service_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('base_volume_mono', models.IntegerField(blank=True, null=True)),
                ('base_rate_mono', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('base_volume_color', models.IntegerField(blank=True, null=True)),
                ('base_rate_color', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Printer')),
                ('proposalTCO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.ProposalTCO')),
            ],
        ),
        migrations.AddField(
            model_name='proposaltco',
            name='management_assumptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.ManagementAssumption'),
        ),
        migrations.AddField(
            model_name='proposaltco',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Proposal'),
        ),
    ]
