# Generated by Django 2.2.1 on 2019-11-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0069_auto_20191005_0130'),
        ('mps', '0071_auto_20191030_1148'),
    ]

    operations = [
    ]
