# Generated by Django 2.2.4 on 2019-10-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0071_auto_20191022_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaltco',
            name='client',
        ),
        migrations.RemoveField(
            model_name='proposaltco',
            name='contract_service_level',
        ),
        migrations.RemoveField(
            model_name='proposaltco',
            name='default_toner_type',
        ),
        migrations.RemoveField(
            model_name='proposaltco',
            name='management_assumptions',
        ),
    ]
