# Generated by Django 2.2.1 on 2019-11-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0073_auto_20191108_0109'),
        ('mps', '0072_auto_20191025_1314'),
    ]

    operations = [
    ]
