# Generated by Django 2.2.1 on 2020-02-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0075_proposal_auto_populate_base_info'),
        ('mps', '0075_auto_20191201_1820'),
    ]

    operations = [
    ]
