# Generated by Django 2.2.4 on 2020-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
      ('mps', '0077_proposaltcoitem_monthly_lease_payment')
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='original_proposal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='IP_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='asset_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='building',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='floor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='location_remarks',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='room',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='schedule',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='transfer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='transfer_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='IP_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='asset_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='building',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='floor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='location_remarks',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='room',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='schedule',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposaltcoitem',
            name='state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
