# Generated by Django 2.2.4 on 2020-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0079_auto_20200214_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalserviceitem',
            name='transfer_color_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='transfer_mono_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
