# Generated by Django 2.2.4 on 2020-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0080_auto_20200224_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='allow_flat_rate',
            field=models.BooleanField(default=False),
        ),
    ]
