# Generated by Django 2.2.4 on 2020-04-07 17:28

from django.db import migrations, models
import mps.models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0081_auto_20200317_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementassumption',
            name='supplies_only',
            field=models.DecimalField(decimal_places=5, default=0.05, max_digits=12, validators=[mps.models.validate_proportion]),
        ),
    ]
