# Generated by Django 2.2.4 on 2020-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0083_managementassumption_cpc_toner_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpurchaseitem',
            name='lease_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
