# Generated by Django 2.2.1 on 2020-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0085_managementassumption_allow_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dca_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
