# Generated by Django 2.2.4 on 2020-05-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0085_managementassumption_allow_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dca_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
