# Generated by Django 2.2.4 on 2020-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0086_company_dca_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementassumption',
            name='managed_cartridge_inflate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
