# Generated by Django 2.2.1 on 2020-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0086_company_dca_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='printercost',
            name='long_model',
            field=models.CharField(max_length=400),
        ),
    ]
