# Generated by Django 2.2.1 on 2020-07-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0087_auto_20200530_0907'),
        ('mps', '0087_managementassumption_managed_cartridge_inflate'),
        ('mps', '0086_company_dca_api_key'),
    ]

    operations = [
    ]
