# Generated by Django 2.2.1 on 2020-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0087_auto_20200530_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signature_image/'),
        ),
    ]
