# Generated by Django 2.2.1 on 2020-08-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0088_proposal_signature_image'),
        ('mps', '0088_merge_20200712_1509'),
    ]

    operations = [
    ]
