# Generated by Django 2.2.1 on 2020-08-30 11:30


from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    companies = apps.get_model('mps', 'company')
    for company in companies.objects.all():
        company.self_service_key = uuid.uuid4()
        company.save()


class Migration(migrations.Migration):
    dependencies = [
        ('mps', '0089_merge_20200830_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='self_service_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='company',
            name='self_service_key',
            field=models.UUIDField(unique=True)
        )
    ]
