# Generated by Django 2.2.1 on 2020-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0090_company_self_service_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='self_service_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
