# Generated by Django 2.2.4 on 2020-08-30 00:23

from django.db import migrations, models
import django.db.models.deletion
import mps.models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0091_auto_20200830_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementassumption',
            name='allow_self_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='self_service_default_sales_rep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='self_service_proposal_type',
            field=models.CharField(default='cpc', max_length=32),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='self_service_service_type',
            field=models.CharField(default='supplies_only', max_length=40),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='self_service_term',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='managementassumption',
            name='self_service_toner_type',
            field=models.CharField(choices=[('OEM', 'OEM'), ('REMAN', 'Reman'), ('OEM_SMP', 'OEM SMP')], default='OEM', max_length=10),
        ),
        migrations.CreateModel(
            name='ModelSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_bluetooth', models.BooleanField(default=False)),
                ('c_ethernet', models.BooleanField(default=False)),
                ('c_usb', models.BooleanField(default=False)),
                ('c_walk_up', models.BooleanField(default=False)),
                ('c_wifi', models.BooleanField(default=False)),
                ('duty_cycle_max', models.IntegerField(default=0)),
                ('duty_cycle_normal', models.IntegerField(default=0)),
                ('f_copy', models.BooleanField(default=False)),
                ('f_fax', models.BooleanField(default=False)),
                ('f_print', models.BooleanField(default=True)),
                ('f_scan', models.BooleanField(default=False)),
                ('mfg_model_number', models.CharField(max_length=32, null=True)),
                ('mfg_model_name', models.CharField(max_length=80)),
                ('o_adf_capacity', models.IntegerField(default=0)),
                ('o_borderless', models.BooleanField(default=False)),
                ('o_duplex', models.BooleanField(default=False)),
                ('o_duplex_scan', models.BooleanField(default=False)),
                ('o_staple', models.BooleanField(default=False)),
                ('o_touchscreen', models.BooleanField(default=False)),
                ('papersize_max', models.CharField(max_length=20)),
                ('papersize_supported', models.CharField(max_length=200, null=True)),
                ('ppm_color', models.IntegerField(default=0)),
                ('ppm_mono', models.IntegerField(default=0)),
                ('print_technology', models.CharField(max_length=32, null=True)),
                ('available', models.BooleanField(default=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Printer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelspecification',
            constraint=models.UniqueConstraint(fields=('mfg_model_name',), name='unique_model_name'),
        ),
    ]
