# Generated by Django 2.2.1 on 2020-11-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0093_modelspecification_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelspecification',
            name='company',
        ),
        migrations.AddField(
            model_name='modelspecification',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
