# Generated by Django 2.2.1 on 2021-01-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0094_auto_20201128_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPS_User_Anon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mps.Company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.MPS_User')),
            ],
            options={
                'verbose_name': 'Company anonymous representative',
                'verbose_name_plural': "Company Anon Rep's",
            },
        ),
    ]
