# Generated by Django 2.2.1 on 2021-01-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0095_mps_user_anon'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementassumption',
            name='sells_hardware',
            field=models.BooleanField(default=True),
        ),
    ]
