# Generated by Django 2.2.1 on 2021-01-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0096_managementassumption_sells_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='retail_color',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='printer',
            name='retail_mono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
