# Generated by Django 2.2.1 on 2021-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0097_auto_20210111_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalserviceitem',
            name='calculated_cpp_color',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposalserviceitem',
            name='calculated_cpp_mono',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
